version: '3.5'

services:
  postgres:
    container_name: hls_postgres
    image: postgres:16.2-alpine3.19

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
